// Generated by gencpp from file movement_general/week_4_srv.msg
// DO NOT EDIT!


#ifndef MOVEMENT_GENERAL_MESSAGE_WEEK_4_SRV_H
#define MOVEMENT_GENERAL_MESSAGE_WEEK_4_SRV_H

#include <ros/service_traits.h>


#include <movement_general/week_4_srvRequest.h>
#include <movement_general/week_4_srvResponse.h>


namespace movement_general
{

struct week_4_srv
{

typedef week_4_srvRequest Request;
typedef week_4_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct week_4_srv
} // namespace movement_general


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::movement_general::week_4_srv > {
  static const char* value()
  {
    return "d8e457fb2df342488e6b3ee3157e64a5";
  }

  static const char* value(const ::movement_general::week_4_srv&) { return value(); }
};

template<>
struct DataType< ::movement_general::week_4_srv > {
  static const char* value()
  {
    return "movement_general/week_4_srv";
  }

  static const char* value(const ::movement_general::week_4_srv&) { return value(); }
};


// service_traits::MD5Sum< ::movement_general::week_4_srvRequest> should match
// service_traits::MD5Sum< ::movement_general::week_4_srv >
template<>
struct MD5Sum< ::movement_general::week_4_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::movement_general::week_4_srv >::value();
  }
  static const char* value(const ::movement_general::week_4_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement_general::week_4_srvRequest> should match
// service_traits::DataType< ::movement_general::week_4_srv >
template<>
struct DataType< ::movement_general::week_4_srvRequest>
{
  static const char* value()
  {
    return DataType< ::movement_general::week_4_srv >::value();
  }
  static const char* value(const ::movement_general::week_4_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::movement_general::week_4_srvResponse> should match
// service_traits::MD5Sum< ::movement_general::week_4_srv >
template<>
struct MD5Sum< ::movement_general::week_4_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::movement_general::week_4_srv >::value();
  }
  static const char* value(const ::movement_general::week_4_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement_general::week_4_srvResponse> should match
// service_traits::DataType< ::movement_general::week_4_srv >
template<>
struct DataType< ::movement_general::week_4_srvResponse>
{
  static const char* value()
  {
    return DataType< ::movement_general::week_4_srv >::value();
  }
  static const char* value(const ::movement_general::week_4_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEMENT_GENERAL_MESSAGE_WEEK_4_SRV_H
