// Generated by gencpp from file movement_general/week_4_srvResponse.msg
// DO NOT EDIT!


#ifndef MOVEMENT_GENERAL_MESSAGE_WEEK_4_SRVRESPONSE_H
#define MOVEMENT_GENERAL_MESSAGE_WEEK_4_SRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace movement_general
{
template <class ContainerAllocator>
struct week_4_srvResponse_
{
  typedef week_4_srvResponse_<ContainerAllocator> Type;

  week_4_srvResponse_()
    : comando()  {
    }
  week_4_srvResponse_(const ContainerAllocator& _alloc)
    : comando(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _comando_type;
  _comando_type comando;





  typedef boost::shared_ptr< ::movement_general::week_4_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movement_general::week_4_srvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct week_4_srvResponse_

typedef ::movement_general::week_4_srvResponse_<std::allocator<void> > week_4_srvResponse;

typedef boost::shared_ptr< ::movement_general::week_4_srvResponse > week_4_srvResponsePtr;
typedef boost::shared_ptr< ::movement_general::week_4_srvResponse const> week_4_srvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movement_general::week_4_srvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movement_general::week_4_srvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::movement_general::week_4_srvResponse_<ContainerAllocator1> & lhs, const ::movement_general::week_4_srvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.comando == rhs.comando;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::movement_general::week_4_srvResponse_<ContainerAllocator1> & lhs, const ::movement_general::week_4_srvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace movement_general

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::movement_general::week_4_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movement_general::week_4_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_general::week_4_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_general::week_4_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_general::week_4_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_general::week_4_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movement_general::week_4_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "20735899cef58c19fdb13abb7f9d907e";
  }

  static const char* value(const ::movement_general::week_4_srvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x20735899cef58c19ULL;
  static const uint64_t static_value2 = 0xfdb13abb7f9d907eULL;
};

template<class ContainerAllocator>
struct DataType< ::movement_general::week_4_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movement_general/week_4_srvResponse";
  }

  static const char* value(const ::movement_general::week_4_srvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movement_general::week_4_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string comando\n"
;
  }

  static const char* value(const ::movement_general::week_4_srvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movement_general::week_4_srvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.comando);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct week_4_srvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movement_general::week_4_srvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movement_general::week_4_srvResponse_<ContainerAllocator>& v)
  {
    s << indent << "comando: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.comando);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEMENT_GENERAL_MESSAGE_WEEK_4_SRVRESPONSE_H
