// Generated by gencpp from file movement_general/week_4_srvRequest.msg
// DO NOT EDIT!


#ifndef MOVEMENT_GENERAL_MESSAGE_WEEK_4_SRVREQUEST_H
#define MOVEMENT_GENERAL_MESSAGE_WEEK_4_SRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace movement_general
{
template <class ContainerAllocator>
struct week_4_srvRequest_
{
  typedef week_4_srvRequest_<ContainerAllocator> Type;

  week_4_srvRequest_()
    : id()
    , torque()  {
      id.assign(0);

      torque.assign(false);
  }
  week_4_srvRequest_(const ContainerAllocator& _alloc)
    : id()
    , torque()  {
  (void)_alloc;
      id.assign(0);

      torque.assign(false);
  }



   typedef boost::array<int16_t, 20>  _id_type;
  _id_type id;

   typedef boost::array<uint8_t, 20>  _torque_type;
  _torque_type torque;





  typedef boost::shared_ptr< ::movement_general::week_4_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movement_general::week_4_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct week_4_srvRequest_

typedef ::movement_general::week_4_srvRequest_<std::allocator<void> > week_4_srvRequest;

typedef boost::shared_ptr< ::movement_general::week_4_srvRequest > week_4_srvRequestPtr;
typedef boost::shared_ptr< ::movement_general::week_4_srvRequest const> week_4_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movement_general::week_4_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movement_general::week_4_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::movement_general::week_4_srvRequest_<ContainerAllocator1> & lhs, const ::movement_general::week_4_srvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.torque == rhs.torque;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::movement_general::week_4_srvRequest_<ContainerAllocator1> & lhs, const ::movement_general::week_4_srvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace movement_general

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::movement_general::week_4_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movement_general::week_4_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_general::week_4_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_general::week_4_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_general::week_4_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_general::week_4_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movement_general::week_4_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d7a63eb1d2cc579afa9e431f303eeef8";
  }

  static const char* value(const ::movement_general::week_4_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd7a63eb1d2cc579aULL;
  static const uint64_t static_value2 = 0xfa9e431f303eeef8ULL;
};

template<class ContainerAllocator>
struct DataType< ::movement_general::week_4_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movement_general/week_4_srvRequest";
  }

  static const char* value(const ::movement_general::week_4_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movement_general::week_4_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16[20] id\n"
"bool[20] torque\n"
;
  }

  static const char* value(const ::movement_general::week_4_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movement_general::week_4_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.torque);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct week_4_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movement_general::week_4_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movement_general::week_4_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "id[]" << std::endl;
    for (size_t i = 0; i < v.id.size(); ++i)
    {
      s << indent << "  id[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.id[i]);
    }
    s << indent << "torque[]" << std::endl;
    for (size_t i = 0; i < v.torque.size(); ++i)
    {
      s << indent << "  torque[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.torque[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEMENT_GENERAL_MESSAGE_WEEK_4_SRVREQUEST_H
