// Generated by gencpp from file sem_02/msgpersonalizada.msg
// DO NOT EDIT!


#ifndef SEM_02_MESSAGE_MSGPERSONALIZADA_H
#define SEM_02_MESSAGE_MSGPERSONALIZADA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sem_02
{
template <class ContainerAllocator>
struct msgpersonalizada_
{
  typedef msgpersonalizada_<ContainerAllocator> Type;

  msgpersonalizada_()
    : id(0)
    , position(0.0)
    , torque(false)  {
    }
  msgpersonalizada_(const ContainerAllocator& _alloc)
    : id(0)
    , position(0.0)
    , torque(false)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef float _position_type;
  _position_type position;

   typedef uint8_t _torque_type;
  _torque_type torque;





  typedef boost::shared_ptr< ::sem_02::msgpersonalizada_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sem_02::msgpersonalizada_<ContainerAllocator> const> ConstPtr;

}; // struct msgpersonalizada_

typedef ::sem_02::msgpersonalizada_<std::allocator<void> > msgpersonalizada;

typedef boost::shared_ptr< ::sem_02::msgpersonalizada > msgpersonalizadaPtr;
typedef boost::shared_ptr< ::sem_02::msgpersonalizada const> msgpersonalizadaConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sem_02::msgpersonalizada_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sem_02::msgpersonalizada_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sem_02::msgpersonalizada_<ContainerAllocator1> & lhs, const ::sem_02::msgpersonalizada_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.position == rhs.position &&
    lhs.torque == rhs.torque;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sem_02::msgpersonalizada_<ContainerAllocator1> & lhs, const ::sem_02::msgpersonalizada_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sem_02

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sem_02::msgpersonalizada_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sem_02::msgpersonalizada_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sem_02::msgpersonalizada_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sem_02::msgpersonalizada_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sem_02::msgpersonalizada_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sem_02::msgpersonalizada_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sem_02::msgpersonalizada_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ee4115f728c0f01ff5b249b23c5266d5";
  }

  static const char* value(const ::sem_02::msgpersonalizada_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xee4115f728c0f01fULL;
  static const uint64_t static_value2 = 0xf5b249b23c5266d5ULL;
};

template<class ContainerAllocator>
struct DataType< ::sem_02::msgpersonalizada_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sem_02/msgpersonalizada";
  }

  static const char* value(const ::sem_02::msgpersonalizada_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sem_02::msgpersonalizada_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n"
"float32 position\n"
"bool torque\n"
;
  }

  static const char* value(const ::sem_02::msgpersonalizada_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sem_02::msgpersonalizada_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.position);
      stream.next(m.torque);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msgpersonalizada_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sem_02::msgpersonalizada_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sem_02::msgpersonalizada_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "position: ";
    Printer<float>::stream(s, indent + "  ", v.position);
    s << indent << "torque: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.torque);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEM_02_MESSAGE_MSGPERSONALIZADA_H
