// Generated by gencpp from file sem_03/srvpersonalizadoRequest.msg
// DO NOT EDIT!


#ifndef SEM_03_MESSAGE_SRVPERSONALIZADOREQUEST_H
#define SEM_03_MESSAGE_SRVPERSONALIZADOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sem_03
{
template <class ContainerAllocator>
struct srvpersonalizadoRequest_
{
  typedef srvpersonalizadoRequest_<ContainerAllocator> Type;

  srvpersonalizadoRequest_()
    : id()
    , position()
    , torque()  {
      id.assign(0);

      position.assign(0.0);

      torque.assign(false);
  }
  srvpersonalizadoRequest_(const ContainerAllocator& _alloc)
    : id()
    , position()
    , torque()  {
  (void)_alloc;
      id.assign(0);

      position.assign(0.0);

      torque.assign(false);
  }



   typedef boost::array<int32_t, 20>  _id_type;
  _id_type id;

   typedef boost::array<float, 20>  _position_type;
  _position_type position;

   typedef boost::array<uint8_t, 20>  _torque_type;
  _torque_type torque;





  typedef boost::shared_ptr< ::sem_03::srvpersonalizadoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sem_03::srvpersonalizadoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct srvpersonalizadoRequest_

typedef ::sem_03::srvpersonalizadoRequest_<std::allocator<void> > srvpersonalizadoRequest;

typedef boost::shared_ptr< ::sem_03::srvpersonalizadoRequest > srvpersonalizadoRequestPtr;
typedef boost::shared_ptr< ::sem_03::srvpersonalizadoRequest const> srvpersonalizadoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sem_03::srvpersonalizadoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sem_03::srvpersonalizadoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sem_03::srvpersonalizadoRequest_<ContainerAllocator1> & lhs, const ::sem_03::srvpersonalizadoRequest_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.position == rhs.position &&
    lhs.torque == rhs.torque;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sem_03::srvpersonalizadoRequest_<ContainerAllocator1> & lhs, const ::sem_03::srvpersonalizadoRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sem_03

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sem_03::srvpersonalizadoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sem_03::srvpersonalizadoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sem_03::srvpersonalizadoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sem_03::srvpersonalizadoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sem_03::srvpersonalizadoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sem_03::srvpersonalizadoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sem_03::srvpersonalizadoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "34efc34b85cc7534e3dc9b2fd749c78f";
  }

  static const char* value(const ::sem_03::srvpersonalizadoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x34efc34b85cc7534ULL;
  static const uint64_t static_value2 = 0xe3dc9b2fd749c78fULL;
};

template<class ContainerAllocator>
struct DataType< ::sem_03::srvpersonalizadoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sem_03/srvpersonalizadoRequest";
  }

  static const char* value(const ::sem_03::srvpersonalizadoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sem_03::srvpersonalizadoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[20] id\n"
"float32[20] position\n"
"bool[20] torque\n"
;
  }

  static const char* value(const ::sem_03::srvpersonalizadoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sem_03::srvpersonalizadoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.position);
      stream.next(m.torque);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct srvpersonalizadoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sem_03::srvpersonalizadoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sem_03::srvpersonalizadoRequest_<ContainerAllocator>& v)
  {
    s << indent << "id[]" << std::endl;
    for (size_t i = 0; i < v.id.size(); ++i)
    {
      s << indent << "  id[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.id[i]);
    }
    s << indent << "position[]" << std::endl;
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      s << indent << "  position[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.position[i]);
    }
    s << indent << "torque[]" << std::endl;
    for (size_t i = 0; i < v.torque.size(); ++i)
    {
      s << indent << "  torque[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.torque[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEM_03_MESSAGE_SRVPERSONALIZADOREQUEST_H
