// Generated by gencpp from file sem_03/srvpersonalizadoResponse.msg
// DO NOT EDIT!


#ifndef SEM_03_MESSAGE_SRVPERSONALIZADORESPONSE_H
#define SEM_03_MESSAGE_SRVPERSONALIZADORESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sem_03
{
template <class ContainerAllocator>
struct srvpersonalizadoResponse_
{
  typedef srvpersonalizadoResponse_<ContainerAllocator> Type;

  srvpersonalizadoResponse_()
    : engine_off()  {
      engine_off.assign(false);
  }
  srvpersonalizadoResponse_(const ContainerAllocator& _alloc)
    : engine_off()  {
  (void)_alloc;
      engine_off.assign(false);
  }



   typedef boost::array<uint8_t, 20>  _engine_off_type;
  _engine_off_type engine_off;





  typedef boost::shared_ptr< ::sem_03::srvpersonalizadoResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sem_03::srvpersonalizadoResponse_<ContainerAllocator> const> ConstPtr;

}; // struct srvpersonalizadoResponse_

typedef ::sem_03::srvpersonalizadoResponse_<std::allocator<void> > srvpersonalizadoResponse;

typedef boost::shared_ptr< ::sem_03::srvpersonalizadoResponse > srvpersonalizadoResponsePtr;
typedef boost::shared_ptr< ::sem_03::srvpersonalizadoResponse const> srvpersonalizadoResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sem_03::srvpersonalizadoResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sem_03::srvpersonalizadoResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sem_03::srvpersonalizadoResponse_<ContainerAllocator1> & lhs, const ::sem_03::srvpersonalizadoResponse_<ContainerAllocator2> & rhs)
{
  return lhs.engine_off == rhs.engine_off;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sem_03::srvpersonalizadoResponse_<ContainerAllocator1> & lhs, const ::sem_03::srvpersonalizadoResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sem_03

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sem_03::srvpersonalizadoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sem_03::srvpersonalizadoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sem_03::srvpersonalizadoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sem_03::srvpersonalizadoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sem_03::srvpersonalizadoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sem_03::srvpersonalizadoResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sem_03::srvpersonalizadoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "87d365418dd3239880b4b6b67e5bba53";
  }

  static const char* value(const ::sem_03::srvpersonalizadoResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x87d365418dd32398ULL;
  static const uint64_t static_value2 = 0x80b4b6b67e5bba53ULL;
};

template<class ContainerAllocator>
struct DataType< ::sem_03::srvpersonalizadoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sem_03/srvpersonalizadoResponse";
  }

  static const char* value(const ::sem_03::srvpersonalizadoResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sem_03::srvpersonalizadoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool[20] engine_off\n"
;
  }

  static const char* value(const ::sem_03::srvpersonalizadoResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sem_03::srvpersonalizadoResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.engine_off);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct srvpersonalizadoResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sem_03::srvpersonalizadoResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sem_03::srvpersonalizadoResponse_<ContainerAllocator>& v)
  {
    s << indent << "engine_off[]" << std::endl;
    for (size_t i = 0; i < v.engine_off.size(); ++i)
    {
      s << indent << "  engine_off[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.engine_off[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEM_03_MESSAGE_SRVPERSONALIZADORESPONSE_H
