// Generated by gencpp from file sem_03/srvpersonalizado.msg
// DO NOT EDIT!


#ifndef SEM_03_MESSAGE_SRVPERSONALIZADO_H
#define SEM_03_MESSAGE_SRVPERSONALIZADO_H

#include <ros/service_traits.h>


#include <sem_03/srvpersonalizadoRequest.h>
#include <sem_03/srvpersonalizadoResponse.h>


namespace sem_03
{

struct srvpersonalizado
{

typedef srvpersonalizadoRequest Request;
typedef srvpersonalizadoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srvpersonalizado
} // namespace sem_03


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sem_03::srvpersonalizado > {
  static const char* value()
  {
    return "2aeb07974f134949a54c8d91a307e998";
  }

  static const char* value(const ::sem_03::srvpersonalizado&) { return value(); }
};

template<>
struct DataType< ::sem_03::srvpersonalizado > {
  static const char* value()
  {
    return "sem_03/srvpersonalizado";
  }

  static const char* value(const ::sem_03::srvpersonalizado&) { return value(); }
};


// service_traits::MD5Sum< ::sem_03::srvpersonalizadoRequest> should match
// service_traits::MD5Sum< ::sem_03::srvpersonalizado >
template<>
struct MD5Sum< ::sem_03::srvpersonalizadoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sem_03::srvpersonalizado >::value();
  }
  static const char* value(const ::sem_03::srvpersonalizadoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sem_03::srvpersonalizadoRequest> should match
// service_traits::DataType< ::sem_03::srvpersonalizado >
template<>
struct DataType< ::sem_03::srvpersonalizadoRequest>
{
  static const char* value()
  {
    return DataType< ::sem_03::srvpersonalizado >::value();
  }
  static const char* value(const ::sem_03::srvpersonalizadoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sem_03::srvpersonalizadoResponse> should match
// service_traits::MD5Sum< ::sem_03::srvpersonalizado >
template<>
struct MD5Sum< ::sem_03::srvpersonalizadoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sem_03::srvpersonalizado >::value();
  }
  static const char* value(const ::sem_03::srvpersonalizadoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sem_03::srvpersonalizadoResponse> should match
// service_traits::DataType< ::sem_03::srvpersonalizado >
template<>
struct DataType< ::sem_03::srvpersonalizadoResponse>
{
  static const char* value()
  {
    return DataType< ::sem_03::srvpersonalizado >::value();
  }
  static const char* value(const ::sem_03::srvpersonalizadoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SEM_03_MESSAGE_SRVPERSONALIZADO_H
